import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import Navbar from "@/components/Navbar";
import { getPublicBook } from "@/lib/app-core/book-reviews";

export const dynamic = "force-dynamic";
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const data=await getPublicBook(slug);if(!data)return{title:"Book"};return{title:`${data.book.title} by ${data.book.author}`,description:`Read Pages & Peace community reviews of ${data.book.title} by ${data.book.author}.`};}
export default async function BookPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const data=await getPublicBook(slug);if(!data)notFound();const avg=data.reviews.length?data.reviews.reduce((s,r)=>s+r.rating,0)/data.reviews.length:0;return <><Navbar/><main className="min-h-screen bg-[#FAF6F1] text-[#17221f]"><section className="border-b bg-white"><div className="mx-auto max-w-5xl px-6 py-14"><Link href="/book-reviews" className="text-sm text-[#189458] underline">← Book reviews</Link><p className="mt-8 text-sm uppercase tracking-widest text-neutral-500">Community book</p><h1 className="mt-2 text-4xl font-semibold md:text-5xl">{data.book.title}</h1><p className="mt-2 text-xl text-neutral-600">by {data.book.author}</p>{data.reviews.length?<p className="mt-5 font-semibold text-[#189458]">★ {avg.toFixed(1)} · {data.reviews.length} review{data.reviews.length===1?"":"s"}</p>:null}<Link href="/dashboard/reviews/new" className="mt-7 inline-flex rounded-full bg-[#17221f] px-5 py-3 font-semibold text-white">Review this book</Link></div></section><section className="mx-auto max-w-5xl px-6 py-12"><h2 className="text-2xl font-semibold">Reader reviews</h2><div className="mt-6 space-y-5">{data.reviews.map(r=><article key={r.id} className="rounded-2xl border bg-white p-6"><div className="flex justify-between gap-4"><div><p className="font-semibold">{r.reviewer.name}</p><p className="mt-1 tracking-widest text-[#189458]" aria-label={`${r.rating} out of 5 stars`}>{"★".repeat(r.rating)}</p></div><time className="text-sm text-neutral-500">{new Date(r.created_at).toLocaleDateString("en-GB")}</time></div>{r.contains_spoilers?<p className="mt-4 inline-block rounded-full bg-amber-100 px-3 py-1 text-xs font-semibold text-amber-900">Contains spoilers</p>:null}<p className="mt-4 whitespace-pre-wrap leading-7 text-neutral-700">{r.body}</p>{r.image_url?<div className="relative mt-5 aspect-[16/9] max-w-2xl overflow-hidden rounded-xl"><Image src={r.image_url} alt="" fill className="object-cover"/></div>:null}</article>)}</div></section></main></>;}
