export const runtime = "nodejs";
export const dynamic = "force-dynamic";

import { NextRequest, NextResponse } from "next/server";
import { supabaseServer } from "@/lib/supabase/server";

const TABLE_MAP = {
  genre: "genres",
  vibe: "vibes",
  theme: "themes",
} as const;

type ClassificationType = keyof typeof TABLE_MAP;

export async function POST(req: NextRequest) {
  console.log("🟢 CREATE CLASSIFICATION ROUTE HIT");

  try {
    const supabase = await supabaseServer();

    /* -------------------------
       AUTH
    ------------------------- */
    const { data: auth } = await supabase.auth.getUser();
    if (!auth?.user) {
      return NextResponse.json(
        { error: "Not authenticated" },
        { status: 401 }
      );
    }

    const { data: profile } = await supabase
      .from("users")
      .select("id, role")
      .eq("auth_user_id", auth.user.id)
      .single();

    if (!profile || profile.role !== "admin") {
      return NextResponse.json(
        { error: "Admins only" },
        { status: 403 }
      );
    }

    /* -------------------------
       BODY
    ------------------------- */
    const {
      type,
      name,
      description,
    }: {
      type?: ClassificationType;
      name?: string;
      description?: string | null;
    } = await req.json();

    if (!type || !name) {
      return NextResponse.json(
        { error: "Missing type or name" },
        { status: 400 }
      );
    }

    const table = TABLE_MAP[type];
    if (!table) {
      return NextResponse.json(
        { error: "Invalid classification type" },
        { status: 400 }
      );
    }

    const cleanName = name.trim();
    if (!cleanName) {
      return NextResponse.json(
        { error: "Empty name" },
        { status: 400 }
      );
    }

    /* -------------------------
       ENFORCE DESCRIPTION (AI SAFETY)
    ------------------------- */
    if (!description || !description.trim()) {
      console.warn("❌ Missing description for AI-created classification");
      return NextResponse.json(
        { error: "Description is required for classification creation" },
        { status: 400 }
      );
    }

    /* -------------------------
       CHECK EXISTING
    ------------------------- */
    const { data: existing, error: existingErr } = await supabase
      .from(table)
      .select("id, name, description")
      .ilike("name", cleanName)
      .maybeSingle();

    if (existingErr) {
      return NextResponse.json(
        { error: existingErr.message },
        { status: 500 }
      );
    }

    if (existing) {
      return NextResponse.json(existing);
    }

    /* -------------------------
       INSERT (UUID GENERATED BY DB)
    ------------------------- */
    const insertPayload = {
      name: cleanName,
      description: description.trim(),
    };

    const { data, error } = await supabase
      .from(table)
      .insert(insertPayload)
      .select("id, name, description")
      .single();

    if (error) {
      console.error("❌ INSERT FAILED:", {
        table,
        payload: insertPayload,
        code: error.code,
        message: error.message,
        details: error.details,
        hint: error.hint,
      });

      return NextResponse.json(
        { error: error.message },
        { status: 500 }
      );
    }

    console.log("✅ INSERT SUCCESS:", data);
    return NextResponse.json(data);
  } catch (err) {
    console.error("💥 CREATE CLASSIFICATION CRASH:", err);
    return NextResponse.json(
      { error: "Server error" },
      { status: 500 }
    );
  }
}
